[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
configure = { package = "config", version = "0.13.3", default-features = false, features = ["ron", "toml"] }
ron = "0.8"

[lib]
name = "shared"
path = "src/lib.rs"
